<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLibrary\Common.Authorization\Common.Authorization.csproj" />
    <ProjectReference Include="..\CommonLibrary\Common.UnitOfWork\Common.UnitOfWork.csproj" />
    <ProjectReference Include="..\CommonLibrary\Common.Utils\Common.Utils.csproj" />
    <ProjectReference Include="..\DomainService\DomainService.csproj" />
    <ProjectReference Include="..\Model\Entity\Entity.csproj" />
    <ProjectReference Include="..\Model\Model\Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.1" />
    <PackageReference Include="Microsoft.Exchange.WebServices" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.10" />
    <PackageReference Include="Microsoft.Graph" Version="5.79.0" />
  </ItemGroup>

</Project>
